[package]
name = "modular-mqtt-protocol-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
bytes = "1"

[dependencies.modular-mqtt-protocol]
path = ".."

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fixed_header"
path = "fuzz_targets/fixed_header.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1

[workspace]
