[package]
name = "modular-mqtt"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = "1.12.1"
modular-mqtt-protocol = { path = "../modular_mqtt_protocol" }
thiserror = "2.0.11"
tokio = { version = "1.42.0", features = ["full"], optional=true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
futures = { version = "0.3.34", features = ["executor"] }
ntest = "0.9.3"
testcontainers = { version = "0.27.3", features = ["blocking"] }
testcontainers-modules = { version = "0.15.0", features = ["mosquitto"] }

[features]
default = ["async"]
# default = []
async = ["dep:tokio"]
